// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseApp():Promise<void>;

export function ExpandHUD():Promise<void>;

export function MinimizeHUD():Promise<void>;

export function MoveHUD(arg1:number,arg2:number):Promise<void>;

export function SendMessage(arg1:string):Promise<string>;
