// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseApp() {
  return window['go']['main']['App']['CloseApp']();
}

export function ExpandHUD() {
  return window['go']['main']['App']['ExpandHUD']();
}

export function MinimizeHUD() {
  return window['go']['main']['App']['MinimizeHUD']();
}

export function MoveHUD(arg1, arg2) {
  return window['go']['main']['App']['MoveHUD'](arg1, arg2);
}

export function SendMessage(arg1) {
  return window['go']['main']['App']['SendMessage'](arg1);
}
